apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding 
metadata: 
  name: mybinding
subjects:		       #define user details 
- kind: user		   #user
  name: suraj		   #user name
  apiGroup: "rbac.authorization.k8s.io/v1
roleRef:
  kind: Role
  name: myrole
  apiGroup: "rbac.authorization.k8s.io/v1"
