apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  selector:
    matchLabels:
      app: mydeploy
  template:
    metadata:
      labels:
        app: mydeploy
    spec:
      containers:
      - name: myapp
        image: httpd
        ports:
        - containerPort: 80
