apiVersion: v1
kind: Pod
metadata:
  name: mynginx
  labels: 
    app: myapp
spec:
 containers:
   - name: mynginx
     image: nginx:latest
     resources:
     request:
       memory: "254Mi"
       cpu: "200m"
     limits:
       memory: "128Mi"
       cpu: "500m"
     ports:
      - name: httpd
        containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mynginx-svc
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80
