apiVersion: v1
kind: Pod
metadata:
  name: mynginx1
  labels: 
    app: myapp
spec:
 containers:
   - name: mynginx1
     image: nginx:latest
     ports:
      - name: httpd
        containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mynginx-svc
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80
