apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
  labels:
   app: myapp2
   
spec: 
  replicas: 3
  selector:
     app: myapp2
  template:
    metadata:
      name: myapp2
      labels:
        app: myapp2
    spec:
      containers:
        - name: httpd
          image: 
          ports:
           - name: httpd-port
             containerPort: 80

