apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplicationC
  labels:
   app: myapp
spec: 
  replicas: 3
  selector:
     app: myapp
  template:
    metadata:
      name: myreplicationC
      labels:
        app: myapp
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
           - name: httpd-port
             containerPort: 80

