apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplicationC
  labels:
   app: myapp
spec: 
  replica: 3
selector:
 template:
   metadata:
     name: myreplicationCpod
     labels:
       app: myapp
   spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - name: httpd-port
              containerPort: 80

