apiVersion: v1
kind: Pod
metadata:
  name: myvolume
  labels:
    name: myvolume
spec:
  volumes: 
    -  mypv
    persistentVolumeClai
  containers:
  - name: myvolume
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
