apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: 5G
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
